CREATE TABLE users(
id INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
first_name VARCHAR NOT NULL ,
last_name VARCHAR NOT NULL ,
email VARCHAR NOT NULL UNIQUE,
age INT ,
address VARCHAR NOT NULL,
join_date VARCHAR NOT NULL
);